services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comptaease_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build:
      context: ./backend
    environment:
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=comptaease_db;Username=postgres;Password=postgres
      Jwt__Secret: dev_super_secret_please_change
      Mail__Host: smtp
      Mail__Port: 587
      Mail__UseSsl: "false"
      Mail__Username: ""
      Mail__Password: ""
      Mail__From: noreply@comptaease.test
    depends_on:
      - db
    volumes:
      - bulletins:/app/wwwroot/bulletins
  web:
    build:
      context: ./frontend
    expose:
      - "80"
  nginx:
    image: nginx:alpine
    depends_on:
      - web
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - bulletins:/usr/share/nginx/html/bulletins:ro
      # - /etc/letsencrypt/live/DOMAIN/fullchain.pem:/etc/letsencrypt/live/DOMAIN/fullchain.pem:ro
      # - /etc/letsencrypt/live/DOMAIN/privkey.pem:/etc/letsencrypt/live/DOMAIN/privkey.pem:ro

volumes:
  db_data:
  bulletins: